services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - thenetwork

  migration:
    build: .
    container_name: migration
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:root@mongodb:27017/
    networks:
      - thenetwork

volumes:
  mongo_data:

networks:
  thenetwork:
    driver: bridge